### ISSUE TITLE
update checks broken

### ISSUE THREAD

**Issue by jmozd** [ZUGFeRD/quba-viewer#66]
Quba-1.4.0.AppImage on Linux started on command line, reports the following after startup:

```
Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/ZUGFeRD/quba-viewer/releases/download/v1.4.0/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/ZUGFeRD/quba-viewer/releases/download/v1.4.0/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Thu, 12 Sep 2024 18:57:45 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "E7A2:5D967:3EB3A3B:3FBEF39:66E339A8"
}
    at createHttpError (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:527:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6917)
    at SimpleURLLoaderWrapper.emit (node:events:527:28)
    at Object.newError (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:47:19)
    at fetchData (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:102:50)
    at async GitHubProvider.getLatestVersion (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:109:23)
    at async AppImageUpdater.getUpdateInfoAndProvider (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:305:19)
    at async AppImageUpdater.doCheckForUpdates (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:319:24)
(node:25336) UnhandledPromiseRejectionWarning: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/ZUGFeRD/quba-viewer/releases/download/v1.4.0/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/ZUGFeRD/quba-viewer/releases/download/v1.4.0/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Thu, 12 Sep 2024 18:57:45 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "E7A2:5D967:3EB3A3B:3FBEF39:66E339A8"
}
    at createHttpError (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:527:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6917)
    at SimpleURLLoaderWrapper.emit (node:events:527:28)
    at Object.newError (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:47:19)
    at fetchData (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:102:50)
    at async GitHubProvider.getLatestVersion (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:109:23)
    at async AppImageUpdater.getUpdateInfoAndProvider (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:305:19)
    at async AppImageUpdater.doCheckForUpdates (/tmp/.mount_Quba-1PVjaQZ/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:319:24)
(Use `quba --trace-warnings ...` to show where the warning was created)
(node:25336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
according to the URL, this seems to be some check for the existence of newer versions - but the checked URL is not present on Github. Seems like electron builder didn't generate that file?

**Comment by jstaerk** [comment]
The files are generated in the publish workflow, correct but we started that on windows, re-run it on the mac and tried to upload the files which were additionally generated. Must have missed a file. Will try to run a complete workflow on the mac from the beginning to the end next time.

**Comment by jmozd** [comment]
@jstaerk Thank you for looking into this. Please note that my report is for Linux, not Mac.

**Comment by jstaerk** [comment]
I know and thats the only platform that can actually be built from windows, sorry, might have accidentally have used a  --win instead of --win --linux at first and then only uploaded the binary. Will try to remember the latest-<anyplatform>.yml next time

**Comment by jmozd** [comment]
Happens with 1.4.2, too:

```
Checking for update
Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/ZUGFeRD/quba-viewer/releases/download/v1.4.2/latest-linux.yml): HttpError: 404 
```
